### PR TITLE
MAPI-1421: upgrading to Play 2.5

### PR DESCRIPTION
**Pull request by agulowaty**
* Removed charset asserts in ReportIntegrationSpec since Play 2.5 no longer sends utf-8 as default. 

cc @alexduf @davidfurey

### CODE REVIEW

**Comment by alexduf** [comment]
That was rather painless! :+1:

**Comment by agulowaty** [comment]
@alexduf: I've added scripts for application.conf s3 copy - please take a look again (tested on CODE)

**Comment by alexduf** [comment]
Still looks good!

**Comment by agulowaty** [comment]
I fixed logging in backup project - logback implementation was missing on classpath and application needs to accept external config file as parameter

**Pull request merged**
