### PR TITLE
MSS-613: Use last modified as an epoch

### PR DESCRIPTION
**Pull request by markrichardsg**

### CODE REVIEW

**Comment by NathanielBennett** [comment]
Er, fix the tests, obviously. But it doesn't seem unreasoable

**Comment by alexduf** [comment]
Why?

**Comment by NathanielBennett** [comment]
@alexduf we can't migrate a datetime column. Life sucks. You and @markrichardsg  should probably have a chat later. Feel free to dial me in

**Comment by markrichardsg** [comment]
https://docs.aws.amazon.com/dms/latest/userguide/CHAP_Source.PostgreSQL.html
In section _Limitations on Using a PostgreSQL Database as a Source for AWS DMS_
_Timestamp with a time zone type column is not supported._

**Pull request closed without merging**
