### PR TITLE
Prefix lambdas with stack name

### PR DESCRIPTION
**Pull request by frankie297**
Make sure all the lambdas in the notification project are prefixed by the stack name - `mobile-notifications`

### CODE REVIEW

**Comment by alexduf** [comment]
I think this also requires a riff-raff change!

**Comment by frankie297** [comment]
> I think this also requires a riff-raff change!

Changed in the code, is there something I need to do in riff-raff to make sure this change happens?

**Comment by alexduf** [comment]
I guess trying to deploy `notificationworkerlambda` ?

**Comment by frankie297** [comment]
@alexduf Just tried testing this in CODE and by prefixing the function name with `mobile-notifications` the name becomes too long and fails the build. It must be 64 characters or less. E.g. `mobile-notifications-android-edition-notification-worker-sender` how would you feel about dropping the second `notification`, would the name still make sense to you?

**Comment by alexduf** [comment]
>how would you feel about dropping the second notification, would the name still make sense to you?

I think it makes perfect sense to drop it! you might as well drop it for all the workers

**Comment by frankie297** [comment]
@alexduf or @jacobwinch do the dependency names need to remain the same?, i thought they should match by removing notifications but this failed the deploy, `Missing deployment dependencies ios-worker-cfn` etc. it is expecting `ios-notifications-worker-cfn`is there a step i am missing?

**Comment by alexduf** [comment]
It's because [the dependency name](https://github.com/guardian/mobile-n10n/pull/508/files#diff-9fd2a17e99dede22cfcb7d36094d3481R23) should match [the deployment name](https://github.com/guardian/mobile-n10n/pull/508/files#diff-9fd2a17e99dede22cfcb7d36094d3481R37)

But if you modify the deployment name, you also need to modify the [package name](https://github.com/guardian/mobile-n10n/blob/master/build.sbt#L302)

Told you it wasn't a "small" task :)

**Comment by frankie297** [comment]
> Told you it wasn't a "small" task :)

I am eating humble pie right now

**Comment by frankie297** [comment]
@alexduf 

Me and @jacobwinch have been pairing on this, it would be great to get your eyes on it again. 

For clarity the steps we have taken so far to test in CODE:

1. We updated all the tags manually for all CODE stacks (for `notificationworkerlambda` and `eventconsumer`)
2. We also updated manually the app parameter for all CODE stacks (for `notificationworkerlambda` and `eventconsumer`)
3. Made sure the builds passed in riff-raff on CODE

We will make sure to replicate these steps for PROD, whilst also informing relevant people to not to deploy any builds for a period of time, and turning continuous deployment off in riff-raff whilst we carry out these steps for PROD, and when updating all the lambda names.

**Comment by alexduf** [comment]
Great work!

**Pull request merged**
