### PR TITLE
Play 3.0 upgrade

### PR DESCRIPTION
**Pull request by davidfurey**
## What does this change?

Minimal changes to upgrade to Play 3.0

## Accessibility

-   [ ] [Tested with screen reader](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#screen-reader)
-   [ ] [Navigable with keyboard](https://github.com/guardian/accessibility/blob/main/people-and-technology/02-physical.md#keyboard)
-   [ ] [Colour contrast passed](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#contrast)
-   [ ] [The change doesn't use only colour to convey meaning](https://github.com/guardian/accessibility/blob/main/people-and-technology/03-visual.md#use-of-colour)

### CODE REVIEW

**Comment by davidfurey** [comment]
Tests on Common and API-models haven't been run, and should be before this is merged

**Review by waisingyiu — COMMENTED** [review]
Thank you @davidfurey for upgrading n10n to Play3.0.

I tried sending a test notification on CODE with this branch.  However, the harvester lambda threw this exception and I'm not sure if it is relevant
Screenshot 2024-04-11 at 17 37 28

**Review by waisingyiu — COMMENTED** [review]
I have tested the latest snapshot and a test notification has been sent successfully.

It appears that we have to exclude `com.typesafe.play` bundles explicitly when the project depends on `"ai.x" %% "play-json-extensions"` (because it brings in the old play-json transitively).  I am wondering whether we should also add the exclusion rule to the subproject `notification`, `registration` and `report`?  Or have I missed anything (as the notification and registration API can work properly on CODE)?

**Comment by davidfurey** [comment]
> I have tested the latest snapshot and a test notification has been sent successfully.
> 
> It appears that we have to exclude `com.typesafe.play` bundles explicitly when the project depends on `"ai.x" %% "play-json-extensions"` (because it brings in the old play-json transitively). I am wondering whether we should also add the exclusion rule to the subproject `notification`, `registration` and `report`? Or have I missed anything (as the notification and registration API can work properly on CODE)?

You are correct, the exclusion should also be applied to notification, registration and report. I've pushed a commit with that

**Review by waisingyiu — APPROVED** [review]
I tested the changes by sending a test notification and my app on Android simulator was able to receive it.

Thank you @davidfurey for upgrading the n10n service to Play 3.0

**Comment by davidfurey** [comment]
@waisingyiu do you think we have done sufficient testing to merge this?

**Comment by waisingyiu** [comment]
> @waisingyiu do you think we have done sufficient testing to merge this?

Yes, I think the testing should be sufficient.  I ran the following tests
- sent a request to registration API and received a valid response
- sent a test notification via notification API and it was received on android simulator. The whole notification delivery pipeline should be working
- sent a request to report API and received a valid response
- checked several lambddas - eventconsumer, reportextractor, fakebreakingnews, schedule- and they returned success

I am happy to merge it and keep an eye on it tomorrow morning if it helps?

**Pull request merged**
