### PR TITLE
fixed success code check

### PR DESCRIPTION
**Pull request by agulowaty**

### CODE REVIEW

**Comment by davidfurey** [comment]
Can this covered by a test?

**Comment by agulowaty** [comment]
Apparently we don't have test for this class at all - I'll add one !

**Comment by agulowaty** [comment]
@davidfurey; added unit test covering this case

**Comment by agulowaty** [comment]
@davidfurey: any comments on that or ready to be merged ?

**Comment by davidfurey** [comment]
👍

**Pull request merged**
